# Generated by Django 4.0.5 on 2022-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_post_date_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_info',
            field=models.TextField(max_length=100, verbose_name='Post açıklaması'),
        ),
    ]
