# Generated by Django 4.0.5 on 2022-10-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_post_text_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text_info',
            field=models.TextField(max_length=200, verbose_name='Post açıklaması'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.post', verbose_name='Post')),
            ],
        ),
    ]
